name: flutter_sheet_localization_plus
description: Flutter localization package powered by Google Sheets.
version: 7.0.0-dev.1

homepage: https://github.com/MostafaElswefy/flutter_sheet_localization_plus
repository: https://github.com/MostafaElswefy/flutter_sheet_localization_plus
issue_tracker: https://github.com/MostafaElswefy/flutter_sheet_localization_plus/issues

publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  intl: any
  meta: any

  template_string:
    git:
      url: https://github.com/MostafaElswefy/flutter_sheet_localization_plus.git
      path: template_string