name: localization_builder
description: Localization model builder used by gsheet_localization_generator.

version: 0.16.7

resolution: workspace

homepage: https://github.com/MostafaElswefy/gsheet_localization
repository: https://github.com/MostafaElswefy/gsheet_localization
issue_tracker: https://github.com/MostafaElswefy/gsheet_localization/issues

publish_to: none

topics:
  - flutter
  - localization
  - code-generation
  - i18n

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1                     # https://pub.dev/packages/collection/versions
  dart_style: ">=3.1.6 <=3.1.12"          # https://pub.dev/packages/dart_style/versions
  equatable: ^2.1.0                       # https://pub.dev/packages/equatable/versions
  logging: ^1.3.0                         # https://pub.dev/packages/logging/versions
  meta: any                               # https://pub.dev/packages/meta/versions
  recase: ^4.1.0                          # https://pub.dev/packages/recase/versions
  yaml: ^3.1.3                            # https://pub.dev/packages/yaml/versions

  template_string:
#    path: ../template_string
    git:
      url: https://github.com/MostafaElswefy/gsheet_localization.git
      path: template_string

dev_dependencies:
  lints: ^6.1.0                           # https://pub.dev/packages/lints/versions
  test: ^1.31.2                           # https://pub.dev/packages/test/versions